[package]
name = "EventPass"
version = "0.0.1"
authors = []

[addresses]
eventpass_ticket = "0x42"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-release-v1.10" }

[dev-dependencies]

[build-options]
bytecode_version = "6"


